apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - kind: Mesh
      name: istio
  hostnames: ["backend.default.svc.cluster.local"]
  rules:
    - backendRefs:
        - name: backend
          port: 80
