apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: mesh
spec:
  parentRefs:
    - kind: Mesh
      name: istio
  hostnames: ["frontend.default.svc.cluster.local"]
  rules:
  - backendRefs:
      - name: frontend
        port: 80
