apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: {{ .Release.Name }}
spec:
  parentRefs:
    - name: eg
  hostnames:
    - "{{ .Values.app }}-gateway.default.svc.cluster.local"
    - "{{ .Values.app }}-gateway.default"
    - "{{ .Values.app }}-gateway"
  rules:
  - matches:
      - headers:
          - type: Exact
            name: ot-baggage-branch
            value: "{{ .Values.branch }}"
    backendRefs:
      - name: "{{ .Values.branch }}-{{ .Values.app }}"
        port: 80