apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}
spec:
  parentRefs:
    - kind: Mesh
      name: istio
  hostnames: ["{{ .Values.app }}.default.svc.cluster.local"]
  rules:
  - matches:
      - headers:
          - type: RegularExpression
            name: baggage
            value: ^(.*\s*;)?branch\s*=\s*{{ .Values.branch }}(\s*;.*)?$   
    backendRefs:
      - name: {{ .Values.branch }}-{{ .Values.app }}
        port: 80