apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backend-pr-env
spec:
  generators:
  - pullRequest:
      github:
        owner: katainaka0503
        repo: grpc-pr-env-test-backend
  template:
    metadata:
      name: backend
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd-image-updater.argoproj.io/image-list: app=katainaka0503/grpc-pr-env-test-backend
        argocd-image-updater.argoproj.io/app.update-strategy: latest
        argocd-image-updater.argoproj.io/app.force-update: "true"
        argocd-image-updater.argoproj.io/app.allow-tags: regexp:{{branch}}-.*
        argocd-image-updater.argoproj.io/write-back-method: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/katainaka0503/grpc-pr-env-test-kubernetes.git
        path: manifests/backend/overlays/pr
        targetRevision: master
        kustomize:
          namePrefix: '{{branch}}-'
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
      syncPolicy:
        automated:
          prune: true