apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backend-pr-env-routing
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: katainaka0503
        repo: grpc-pr-env-test-backend
  template:
    metadata:
      name: '{{branch}}-backend-routing'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/katainaka0503/grpc-pr-env-test-kubernetes.git
        path: manifests/pr-env-routing
        targetRevision: master
        helm:
          releaseName: backend-{{ branch }}-pr
          parameters:
            - name: branch
              value: '{{ branch }}'
            - name: app
              value: 
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
      syncPolicy:
        automated:
          prune: true